### ISSUE TITLE
[Question] What's the meaning of a thumbs down icon?

### ISSUE THREAD

**Issue by TheDutchCoder** [ziolko/aria-devtools#11]
I have the following login screen as an example:
![image](https://user-images.githubusercontent.com/1668207/125466879-40fd21e9-551d-4aab-a367-3fbc92d5108d.png)

And I'm wondering what the thumbs down icon means, as there's no hover title to tell me what it is, not can I click it to see more info.

**Comment by ziolko** [comment]
Hi @TheDutchCoder,

The thumbs down/up icon represents the value of the aria-invalid attribute. I will add a tooltip soon to make it clear. 

Does it properly show the valid/invalid state in your case?

Mateusz

**Comment by TheDutchCoder** [comment]
Hi @ziolko ,

That makes perfect sense, thanks!
It does properly show, as far as I can tell yes.

If I'm not mistaken, an empty field will still evaluate to `invalid` if required, so I think it's all good.

Thanks!
