### ISSUE TITLE
[Feature] Add support for the `switch` role

### ISSUE THREAD

**Issue by TheDutchCoder** [ziolko/aria-devtools#12]
Currently the switch role seems to be unsupported:
![image](https://user-images.githubusercontent.com/1668207/128397432-aee296df-2dbe-41aa-a184-03d1d49539d5.png)

**Comment by ziolko** [comment]
Hi @TheDutchCoder,

Thanks for the report. Looking at https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Switch_role it doesn't seem difficult so I think I will add it either on the weekend or early next week.

Mateusz

**Comment by TheDutchCoder** [comment]
Awesome, thanks!

**Comment by TheDutchCoder** [comment]
Looks like you added it in, awesome, thanks!

**Comment by ziolko** [comment]
I am glad you like it! Feel free to star this repository and leave a positive review at [Chrome Web Store](https://chrome.google.com/webstore/detail/aria-devtools/dneemiigcbbgbdjlcdjjnianlikimpck).

As this is something I develop in my free time small things like this keep me motivated 😉

**Comment by TheDutchCoder** [comment]
Done and done ;)

**Comment by ziolko** [comment]
Great, thanks!
