### ISSUE TITLE
First heading one the page should be h1 but is h2

### ISSUE THREAD

**Issue by TheDutchCoder** [ziolko/aria-devtools#16]
This issue pops up when the first heading in the DOM is not an h1.
This is a false positive, because it's totally fine to have an h2 first depending on where it appears in the markup.

For example, a nav element (that usually precedes the main content) should have a heading and this is often an h2 as there really should only be one h1 (reserved for the main content / page title).

It might be better to check for the amount of h1's and/or check it's within the `main` of the page.

More info: https://usability.yale.edu/web-accessibility/articles/headings

**Comment by ziolko** [comment]
Hi @TheDutchCoder, that's exactly the kind of feedback I am looking for. I will release a fix in a few days.

Mateusz

**Comment by ziolko** [comment]
Hi @TheDutchCoder ,

Seems that the issue detection feature creates more problems than it solves. I am disabling this functionality for now, until I figure out how to do it properly.

A new version of ARIA DevTools with this functionality disabled has been released for Chrome and Firefox and should be available very soon.

Hope this helps,
Mateusz
